# .streamlit/secrets.toml
[mysql]
host = "localhost"
port = 3306
database = "pack_db"
user = "root"
password = "mahalo"
# แก้ปัญหา error NotSupportedError: Authentication plugin 'caching_sha2_password' is not supported
#auth_plugin="mysql_native_password"

[mysql2]
host = "192.168.1.10"
port = 3306
database = "pack_db"
user = "root"
password = "mahalo"

